#!/bin/sh
# Nico Schottelius / cinit-example
# Start udev

PATH=/bin:/sbin:/usr/bin:/usr/sbin

UDEVSTART=/sbin/udevstart
UDEVBIN=/sbin/udev
PROC_HOTPLUG=/proc/sys/kernel/hotplug

$UDEVSTART
echo "$UDEVBIN" > "$PROC_HOTPLUG"

mkdir /dev/pts
