.\"     Title: list_ccollect_intervals
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.1 <http://docbook.sf.net/>
.\"      Date: 08/27/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "LIST_CCOLLECT_INTERV" "1" "08/27/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
list_ccollect_intervals - list available intervals from ccollect(1)
.SH "SYNOPSIS"
\fIlist_ccollect_intervals\.sh\fR
.sp
.SH "DESCRIPTION"
list_ccollect_intervals\.sh shows intervals specified in the configuration for ccollect(1)\. It displays the name of each interval, followed by a colon followed by the number backups to keep\.
.sp
.SH "FILES"
.PP
$CCOLLECT_CONF/intervals
.RS 4
Directory containing the intervals\. $CCOLLECT_CONF is
\fI/etc/ccollect\fR, if unset\.
.RE
.SH "SEE ALSO"
add_ccollect_source(1), ccollect(1), ccollect\-logwrapper(1), delete_ccollect_source(1)
.sp
.SH "AUTHOR"
Nico Schottelius <nico\-ccollect\-\-@\-\-schottelius\.org>
.sp
.SH "RESOURCES"
Main web site: http://unix\.schottelius\.org/ccollect/
.sp
.SH "COPYING"
Copyright (C) 2007 Nico Schottelius\. Free use of this software is granted under the terms of the GNU General Public License Version 3 (GPLv3)\.
.sp
.SH "NOTES"
.IP " 1." 4
nico-ccollect--@--schottelius.org
.RS 4
\%mailto:nico-ccollect--@--schottelius.org
.RE
