#!/bin/sh
# Do some testing

echo "Environment:"
echo "------------"
set
echo "------------"
echo "Parameters:"
i=0
while [ $i -le $# ]; do
   eval echo $i: \$$i
   i=$(($i+1))
done
echo "------------"
