.\"     Title: ccollect_analyse_logs
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 03/17/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "CCOLLECT_ANALYSE_LOG" "1" "03/17/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ccollect_analyse_logs - analyse logs produced by ccollect(1)
.SH "SYNOPSIS"
\fIccollect_analyse_logs\.sh\fR [iwe]
.sp
.SH "DESCRIPTION"
ccollect_analyse_logs\.sh reads the logfiles from stdin\. You have to specify at least one of the three loglevels (*i*nformational, *w*arning, *e*rror)\. Any combination of them is allowed\.
.sp
.SH "FILES"
.PP
ccollect log files
.RS 4
Are read from stdin
.RE
.SH "EXAMPLES"
.PP
cat /var/log/ccollect/single/* | ccollect_analyse_logs\.sh iw
.RS 4
Displays warnings and informational parts
.RE
.PP
ccollect_analyse_logs\.sh iw < /var/log/ccollect/all_together
.RS 4
Displays only error messages (useful for the morning mail)
.RE
.SH "SEE ALSO"
ccollect(1), ccollect_add_source\.sh, ccollect_delete_source(1), ccollect_list_intervals(1), ccollect_logwrapper(1),
.sp
.SH "AUTHOR"
Nico Schottelius <nico\-ccollect\-\-@\-\-schottelius\.org>
.sp
.SH "RESOURCES"
Main web site: http://unix\.schottelius\.org/ccollect/
.sp
.SH "COPYING"
Copyright (C) 2007\-2008 Nico Schottelius\. Free use of this software is granted under the terms of the GNU General Public License Version 3 (GPLv3)\.
.sp
.SH "NOTES"
.IP " 1." 4
nico-ccollect--@--schottelius.org
.RS 4
\%mailto:nico-ccollect--@--schottelius.org
.RE
