'\" t
.\"     Title: ccollect_analyse_logs
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 07/08/2009
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "CCOLLECT_ANALYSE_LOG" "1" "07/08/2009" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ccollect_analyse_logs \- analyse logs produced by ccollect(1)
.SH "SYNOPSIS"
.sp
\fIccollect_analyse_logs\&.sh\fR [iwe]
.SH "DESCRIPTION"
.sp
ccollect_analyse_logs\&.sh reads the logfiles from stdin\&. You have to specify at least one of the three loglevels (*i*nformational, *w*arning, *e*rror)\&. Any combination of them is allowed\&.
.SH "FILES"
.PP
ccollect log files
.RS 4
Are read from stdin
.RE
.SH "EXAMPLES"
.PP
cat /var/log/ccollect/single/* | ccollect_analyse_logs\&.sh iw
.RS 4
Displays warnings and informational parts
.RE
.PP
ccollect_analyse_logs\&.sh iw < /var/log/ccollect/all_together
.RS 4
Displays only error messages (useful for the morning mail)
.RE
.SH "SEE ALSO"
.sp
ccollect(1), ccollect_add_source\&.sh, ccollect_delete_source(1), ccollect_list_intervals(1), ccollect_logwrapper(1),
.SH "AUTHOR"
.sp
Nico Schottelius <nico\-ccollect\-\-@\-\-schottelius\&.org>
.SH "RESOURCES"
.sp
Main web site: http://www\&.nico\&.schottelius\&.org/software/ccollect/
.SH "COPYING"
.sp
Copyright (C) 2007\-2008 Nico Schottelius\&. Free use of this software is granted under the terms of the GNU General Public License Version 3 (GPLv3)\&.
