'\" t
.\"     Title: ccollect
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 07/08/2009
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "CCOLLECT" "1" "07/08/2009" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ccollect \- (pseudo) incremental backup with different exclude lists using hardlinks and rsync
.SH "SYNOPSIS"
.sp
\fIccollect\&.sh\fR <interval name> [args] <sources to backup>
.SH "DESCRIPTION"
.sp
ccollect is a backup utility written in the sh\-scripting language\&. It does not depend on a specific shell, only /bin/sh needs to be bourne shell compatibel (like \fIdash\fR, \fIksh\fR, \fIzsh\fR, \fIbash\fR, \&...)\&.
.sp
For more information refer to the manual titled "ccollect \- Installing, Configuring and Using" (available as text (asciidoc), texinfo or html)\&.
.SH "OPTIONS"
.PP
\-h, \-\-help
.RS 4
Show the help screen
.RE
.PP
\-p, \-\-parallel
.RS 4
Parallelise backup processes
.RE
.PP
\-a, \-\-all
.RS 4
Backup all sources specified in /etc/ccollect/sources
.RE
.PP
\-v, \-\-verbose
.RS 4
Be very verbose (uses set \-x)\&.
.RE
.SH "SEE ALSO"
.sp
ccollect_add_source(1), ccollect_analyse_logs(1), ccollect_logwrapper(1) ccollect_delete_source(1), ccollect_list_intervals(1)
.SH "AUTHOR"
.sp
Nico Schottelius <nico\-ccollect\-\-@\-\-schottelius\&.org>
.SH "RESOURCES"
.sp
Main web site: http://www\&.nico\&.schottelius\&.org/software/ccollect/
.SH "COPYING"
.sp
Copyright (C) 2006\-2008 Nico Schottelius\&. Free use of this software is granted under the terms of the GNU General Public License Version 3 (GPLv3)\&.
