--------------------------------------------------------------------------------
replacing your current init system,
Nico Schottelius 2005-06-14 (Last Modified: 2005-06-14)
--------------------------------------------------------------------------------

Simply install cinit (make install), configure cinit
(see configuring.cinit), restart system using
cinit (see README/Installing) delete /sbin/init
and copy cinit to init (cp /sbin/cinit /sbin/init), reboot.

